version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: timborelle/visits-flask
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    volumes:
      - /var/run/docker.sock
    ports:
      - "80:80"
    networks:
      - webnet
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/tmp/:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - webnet
  visualizer: 
    image: dockersamples/visualizer:latest 
    ports: 
      - "8080:8080" 
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock" 
    deploy: 
      placement: 
        constraints: [node.role == manager] 
    networks: 
      - webnet
networks:
  webnet:
#     driver: overlay
