version: '3'
services:
    web:
        image: 'ccorrearestr/nuit2019'
        ports: 
          - '8080:8080'
        depends_on: 
          - api
        networks: 
          - webnet
        links: 
          - 'api:webapi'
    api:
        image: 'ccorrearestr/api'
        ports:
            - '5000:5000'
        volumes:
            - .:/code
        depends_on:
            - mongo
        networks: 
          - webnet
    mongo:
        image: 'mongo'
        container_name: 'mongodb'
        environment: 
          - MONGO_INITDB_DATABASE=db
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=root
        volumes: 
          - ./initmongo.js:/docker-entrypoint-initdb.d/initmongo.js:ro
          - ./mongo-volume:/data/db
        ports: 
          - '27017-27019:27017-27019'
        networks: 
          - webnet

networks:
  webnet:
